"""empty message

Revision ID: 80d19798fbb1
Revises: acff746ceaa5
Create Date: 2018-09-03 11:07:49.703938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d19798fbb1'
down_revision = 'acff746ceaa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'permissions')
    # ### end Alembic commands ###
