"""empty message

Revision ID: 977c40731df4
Revises: 87c6172e0cbd
Create Date: 2018-08-30 15:57:24.201637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '977c40731df4'
down_revision = '87c6172e0cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('desc', sa.String(length=200), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fav_id', sa.Integer(), nullable=True),
    sa.Column('fav_type', sa.Integer(), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('course_orgs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_course_orgs_name'), 'course_orgs', ['name'], unique=True)
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.Column('profession', sa.String(length=6), nullable=True),
    sa.Column('work_years', sa.Integer(), nullable=True),
    sa.Column('work_company', sa.String(length=50), nullable=True),
    sa.Column('work_position', sa.String(length=20), nullable=True),
    sa.Column('points', sa.String(length=50), nullable=True),
    sa.Column('fav_nums', sa.Integer(), nullable=True),
    sa.Column('course_org_id', sa.Integer(), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_org_id'], ['course_orgs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_teachers_name'), 'teachers', ['name'], unique=True)
    op.create_table('lessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('learn_times', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('courses', sa.Column('category', sa.String(length=20), nullable=True))
    op.add_column('courses', sa.Column('courseorg_id', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('degree', sa.String(length=3), nullable=False))
    op.add_column('courses', sa.Column('desc', sa.String(length=256), nullable=True))
    op.add_column('courses', sa.Column('detail', sa.Text(), nullable=True))
    op.add_column('courses', sa.Column('fav_nums', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('image', sa.String(length=100), nullable=True))
    op.add_column('courses', sa.Column('learn_time', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('students', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('tag', sa.String(length=20), nullable=True))
    op.add_column('courses', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('teacher_tell', sa.String(length=300), nullable=True))
    op.add_column('courses', sa.Column('youneed_know', sa.String(length=300), nullable=True))
    op.create_foreign_key(None, 'courses', 'teachers', ['teacher_id'], ['id'])
    op.create_foreign_key(None, 'courses', 'course_orgs', ['courseorg_id'], ['id'])
    op.add_column('users', sa.Column('email', sa.String(length=128), nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'youneed_know')
    op.drop_column('courses', 'teacher_tell')
    op.drop_column('courses', 'teacher_id')
    op.drop_column('courses', 'tag')
    op.drop_column('courses', 'students')
    op.drop_column('courses', 'learn_time')
    op.drop_column('courses', 'image')
    op.drop_column('courses', 'fav_nums')
    op.drop_column('courses', 'detail')
    op.drop_column('courses', 'desc')
    op.drop_column('courses', 'degree')
    op.drop_column('courses', 'courseorg_id')
    op.drop_column('courses', 'category')
    op.drop_table('lessions')
    op.drop_index(op.f('ix_teachers_name'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_course_orgs_name'), table_name='course_orgs')
    op.drop_table('course_orgs')
    op.drop_table('user_favorites')
    op.drop_table('cities')
    # ### end Alembic commands ###
