"""empty message

Revision ID: 9efc44e41f9b
Revises: a9a7d8f887ed
Create Date: 2018-09-25 15:25:11.694379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9efc44e41f9b'
down_revision = 'a9a7d8f887ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('notice', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'notice')
    # ### end Alembic commands ###
