"""empty message

Revision ID: a9a7d8f887ed
Revises: ff346020b581
Create Date: 2018-09-25 15:09:07.960558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9a7d8f887ed'
down_revision = 'ff346020b581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('path', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'path')
    # ### end Alembic commands ###
