"""empty message

Revision ID: acff746ceaa5
Revises: 6adf7339075a
Create Date: 2018-08-31 18:07:29.648090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acff746ceaa5'
down_revision = '6adf7339075a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_favorites', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_favorites', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_favorites', type_='foreignkey')
    op.drop_column('user_favorites', 'user_id')
    # ### end Alembic commands ###
